export const userConstants = {
    UPDATELOCATION:"DOCTORS/UPDATELOCATION",
    GETDOCTOR:"DOCTORS/GETDOCTOR",
    CANCELREQUEST:"DOCTORS/CANCELREQUEST",
    HISTORY:"DOCTORS/HISTORY",
    CLIENTSTATUS:"DOCTORS/CLIENTSTATUS",
    COMPLETEREQUEST:"DOCTORS/COMPLETEREQUEST",
    LABSERVICES:"DOCTORS/LABSERVICES",
    REQUESTLABSERVICE:"REQUESTLABSERVICE",
    CURRENTREQUEST:"DOCTORS/CURRENTREQUEST",
    CANCELLABREQUEST:"DOCTORS/CANCELREQUEST",
    CONFIRMLABREQUEST:"DOCTORS/CONFIRMLABREQUEST",
    ONGOINGREQUEST:"ONGOINGREQUEST",
    ONCOMPLETELABREQUEST:"COMPLETELABREQUEST"
}

export const userHelperConstants = {
    noRequests:"No requests",
    noDoctorAvailable:"No Doctor Available"
}
