export const healthWorkerConstants = {
   UPDATELOCATION:"DOCTORS/UPDATELOCATION",
   LATESTREQUEST:"DOCTORS/LATESTREQUEST",
   CANCELREQUEST:"DOCTORS/CANCELREQUEST",
   ACCEPTREQUEST:"DOCTORS/ACCEPTREQUEST",
   DOCTORHISTORY:"DOCTORS/DOCTORHISTORY",
   COMPLETEREQUEST:"DOCTORS/COMPLETEHISTORY",
   ACTIVATEWORKER:"DOCTORS/ACTIVATEWORKER",
   DEACTIVATEWORKER:"DOCTORS/DEACTIVATEWORKER",
   GETSTATUS:"DOCTORS/STATUS"
}